/**
 * Deploy Service - Multi-platform deployment
 *
 * Supports:
 * - Vercel (via API)
 * - Netlify (via API)
 * - Export ZIP (fallback)
 */

import * as vscode from "vscode";
import * as path from "path";
import JSZip from "jszip";
import { GeneratedFile } from "./previewPanel";

export type DeployPlatform = "vercel" | "netlify" | "zip";

export interface DeployConfig {
  platform: DeployPlatform;
  projectName: string;
  token?: string;
}

export interface DeployResult {
  success: boolean;
  url?: string;
  error?: string;
  platform: DeployPlatform;
}

/**
 * Deploy files to selected platform
 */
export async function deployFiles(
  files: GeneratedFile[],
  config: DeployConfig,
): Promise<DeployResult> {
  switch (config.platform) {
    case "vercel":
      return deployToVercel(files, config);
    case "netlify":
      return deployToNetlify(files, config);
    case "zip":
      return exportToZip(files, config);
    default:
      return {
        success: false,
        error: "Unknown platform",
        platform: config.platform,
      };
  }
}

/**
 * Deploy to Vercel
 */
async function deployToVercel(
  files: GeneratedFile[],
  config: DeployConfig,
): Promise<DeployResult> {
  const token =
    config.token ||
    vscode.workspace.getConfiguration("uigenai").get<string>("vercelToken");

  if (!token) {
    return {
      success: false,
      error:
        "Vercel token not configured. Set it in Settings > UI Gen AI > Vercel Token",
      platform: "vercel",
    };
  }

  try {
    // Prepare files for Vercel API
    const vercelFiles = files.map((f) => ({
      file: f.path,
      data: Buffer.from(f.content).toString("base64"),
      encoding: "base64",
    }));

    // Create deployment
    const response = await fetch("https://api.vercel.com/v13/deployments", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: config.projectName || "ui-gen-app",
        files: vercelFiles,
        projectSettings: {
          framework: "vite",
          buildCommand: "npm run build",
          outputDirectory: "dist",
        },
      }),
    });

    if (!response.ok) {
      const error = await response.text();
      return {
        success: false,
        error: `Vercel API error: ${error}`,
        platform: "vercel",
      };
    }

    const data = await response.json();
    return {
      success: true,
      url: `https://${data.url}`,
      platform: "vercel",
    };
  } catch (e: any) {
    return {
      success: false,
      error: `Vercel deploy failed: ${e.message}`,
      platform: "vercel",
    };
  }
}

/**
 * Deploy to Netlify
 */
async function deployToNetlify(
  files: GeneratedFile[],
  config: DeployConfig,
): Promise<DeployResult> {
  const token =
    config.token ||
    vscode.workspace.getConfiguration("uigenai").get<string>("netlifyToken");

  if (!token) {
    return {
      success: false,
      error:
        "Netlify token not configured. Set it in Settings > UI Gen AI > Netlify Token",
      platform: "netlify",
    };
  }

  try {
    // Create a zip file for Netlify
    const zip = new JSZip();
    for (const file of files) {
      zip.file(file.path, file.content);
    }
    const zipContent = await zip.generateAsync({ type: "arraybuffer" });

    // Deploy to Netlify
    const response = await fetch("https://api.netlify.com/api/v1/sites", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/zip",
      },
      body: zipContent,
    });

    if (!response.ok) {
      const error = await response.text();
      return {
        success: false,
        error: `Netlify API error: ${error}`,
        platform: "netlify",
      };
    }

    const data = await response.json();
    return {
      success: true,
      url: data.ssl_url || data.url,
      platform: "netlify",
    };
  } catch (e: any) {
    return {
      success: false,
      error: `Netlify deploy failed: ${e.message}`,
      platform: "netlify",
    };
  }
}

/**
 * Export to ZIP file
 */
async function exportToZip(
  files: GeneratedFile[],
  config: DeployConfig,
): Promise<DeployResult> {
  try {
    const zip = new JSZip();

    // Add all files to zip
    for (const file of files) {
      zip.file(file.path, file.content);
    }

    // Add a README with deploy instructions
    const readme = `# ${config.projectName || "UI Gen App"}

Generated by UI Gen AI

## Quick Start

\`\`\`bash
# Install dependencies
npm install

# Run development server
npm run dev

# Build for production
npm run build
\`\`\`

## Deploy

### Vercel
\`\`\`bash
npx vercel --prod
\`\`\`

### Netlify
\`\`\`bash
npx netlify deploy --prod --dir=dist
\`\`\`

### GitHub Pages
1. Push to GitHub
2. Enable Pages in repo settings
3. Set source to "GitHub Actions" or "gh-pages" branch
`;
    zip.file("README.md", readme);

    // Generate zip
    const content = await zip.generateAsync({ type: "uint8array" });

    // Save file dialog
    const uri = await vscode.window.showSaveDialog({
      defaultUri: vscode.Uri.file(`${config.projectName || "ui-gen-app"}.zip`),
      filters: { "ZIP files": ["zip"] },
    });

    if (!uri) {
      return {
        success: false,
        error: "Save cancelled",
        platform: "zip",
      };
    }

    await vscode.workspace.fs.writeFile(uri, content);

    return {
      success: true,
      url: uri.fsPath,
      platform: "zip",
    };
  } catch (e: any) {
    return {
      success: false,
      error: `ZIP export failed: ${e.message}`,
      platform: "zip",
    };
  }
}

/**
 * Show deploy platform picker
 */
export async function pickDeployPlatform(): Promise<DeployConfig | undefined> {
  const config = vscode.workspace.getConfiguration("uigenai");
  const vercelToken = config.get<string>("vercelToken");
  const netlifyToken = config.get<string>("netlifyToken");

  const options = [
    {
      label: "$(cloud-upload) Vercel",
      description: vercelToken ? "Token configured" : "Token required",
      value: "vercel" as DeployPlatform,
      hasToken: !!vercelToken,
    },
    {
      label: "$(cloud-upload) Netlify",
      description: netlifyToken ? "Token configured" : "Token required",
      value: "netlify" as DeployPlatform,
      hasToken: !!netlifyToken,
    },
    {
      label: "$(file-zip) Export ZIP",
      description: "Download and deploy manually",
      value: "zip" as DeployPlatform,
      hasToken: true,
    },
  ];

  const pick = await vscode.window.showQuickPick(options, {
    title: "Select Deploy Platform",
    placeHolder: "Where do you want to deploy?",
  });

  if (!pick) {
    return undefined;
  }

  // Check if token is required
  if (!pick.hasToken) {
    const setToken = await vscode.window.showWarningMessage(
      `${pick.value} token is not configured. Would you like to set it now?`,
      "Set Token",
      "Cancel",
    );

    if (setToken === "Set Token") {
      const token = await vscode.window.showInputBox({
        title: `Enter ${pick.value} API Token`,
        password: true,
        placeHolder: "Paste your API token here",
      });

      if (token) {
        await config.update(
          pick.value === "vercel" ? "vercelToken" : "netlifyToken",
          token,
          vscode.ConfigurationTarget.Global,
        );
      } else {
        return undefined;
      }
    } else {
      return undefined;
    }
  }

  // Get project name
  const projectName = await vscode.window.showInputBox({
    title: "Project Name",
    value: "ui-gen-app",
    placeHolder: "e.g., my-dashboard",
  });

  if (!projectName) {
    return undefined;
  }

  return {
    platform: pick.value,
    projectName,
  };
}

/**
 * Show deploy result
 */
export function showDeployResult(result: DeployResult): void {
  if (result.success) {
    if (result.platform === "zip") {
      vscode.window.showInformationMessage(`ZIP exported to: ${result.url}`);
    } else {
      vscode.window
        .showInformationMessage(`Deployed to ${result.platform}!`, "Open URL")
        .then((action) => {
          if (action === "Open URL" && result.url) {
            vscode.env.openExternal(vscode.Uri.parse(result.url));
          }
        });
    }
  } else {
    vscode.window.showErrorMessage(`Deploy failed: ${result.error}`);
  }
}
